---
# tasks file for postgresql

- name: install postgresql on Archlinux
  when: ansible_os_family != "Darwin"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
  tags:
    - postgresql

- name: install postgresql on OSX
  when: ansible_os_family == "Darwin"
  homebrew:
    name: postgresql
    state: latest
  tags:
    - postgresql

- name: create the postgresql user
  become: true
  user:
    name: "{{ postgresql_user }}"
  tags:
    - postgresql

- name: create data directory
  become: true
  file:
    state: directory
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    mode: 0775
  tags:
    - postgresql

- name: check if DB cluster was initialized
  stat:
    path: "{{ postgresql_data_dir }}/postgresql.conf"
  register: already_initdb
  tags:
    - postgresql

- name: initialize DB cluster
  become: true
  become_user: "{{ postgresql_user }}"
  shell: "initdb --locale=$LANG --encoding=UTF8 --pgdata='{{ postgresql_data_dir }}'"
  when: already_initdb.stat.exists == false
  tags:
    - postgresql

- name: configure max_connections
  become: true
  become_user: "{{ postgresql_user }}"
  lineinfile:
    state: present
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: '^#*max_connections'
    line: "max_connections = {{ postgresql_max_connections }}"
  notify: reload postgresql
  tags:
    - postgresql

- name: listen to external connections
  become: true
  become_user: "{{ postgresql_user }}"
  lineinfile:
    state: present
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: '^#* *listen_addresses ='
    line: "listen_addresses = '*'"
  notify: reload postgresql
  when: postgresql_allow_remote_connections
  tags:
    - postgresql

- name: allow connections from other hosts
  become: true
  become_user: "{{ postgresql_user }}"
  blockinfile:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
    block: |
      host all all all md5
  notify: reload postgresql
  when: postgresql_allow_remote_connections
  tags:
    - postgresql

- name: start postgresql
  when: ansible_os_family != "Darwin"
  service:
    name: postgresql
    state: started
  tags:
    - postgresql

- name: add postgresql launch agent
  when: ansible_os_family == "Darwin"
  file:
    src: /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
    dest: "{{ lookup('env','HOME') }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
    state: link
  tags:
    - postgresql

- name: load postgresql launch agent
  when: ansible_os_family == "Darwin"
  shell: launchctl load {{ lookup('env','HOME') }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  tags:
    - postgresql
